name: project20183227
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.0
  firebase_auth: ^4.6.2
  firebase_database_web: ^0.2.3+2
  highlightable: ^1.0.3
  http: ^0.13.4
  device_info: ^2.0.0
  intl: ^0.17.0
  firebase_core: ^2.13.1
  cloud_firestore: 4.8.0
  cloud_firestore_platform_interface: ^5.15.0



  cupertino_icons: ^1.0.2
  scroll_date_picker: ^3.0.0
  flutter_datetime_picker: ^1.5.1
  date_utils: ^0.2.0
  flutter_calendar_carousel: ^2.1.0
  table_calendar: ^3.0.3
  image_picker: ^0.8.8
  firebase_storage: ^11.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/

